name: telegram-bot-fsafe
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
  - Telegram.Bot.FSAfe
  - Telegram.Bot.FSAfe.BotContextParser
  - Telegram.Bot.FSAfe.BotM
  - Telegram.Bot.FSAfe.FSA
  - Telegram.Bot.FSAfe.Reply
  - Telegram.Bot.FSAfe.RunTG
  - Telegram.Bot.FSAfe.Start
  - Telegram.Bot.FSAfe.Start.Internal

  dependencies:
  - base
  - telegram-bot-api
  - first-class-families
  - mtl
  - text
  - servant-client
  - aeson
  - stm
  - async
  - unordered-containers
  - hashable

executables:
  telegram-bot-fsafe-example:
    main: Main.hs
    source-dirs: example
    dependencies:
    - telegram-bot-fsafe
    - telegram-bot-api

    - base
    - mtl
    - text

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
