nix:
  enable: true
  packages:
    - zlib.dev
    - zlib.out

snapshot: lts-23.14

packages:
  - .

extra-deps:
  - git: https://github.com/danielambda/telegram-bot-message-dsl
    commit: ce9da578810ab3f7ac309200e38b067a0faf5e34
